#!/usr/bin/env python3
"""
Build script for Cython compilation of proprietary phase engines.

Compiles the statistical engines and knowledge store into .so / .pyd files
for IP protection. The open-source layer (adapters, CLI, registry) remains
as pure Python.

Usage:
    python build_cython.py              # Build all engines
    python build_cython.py --check      # Verify Cython is available
    python build_cython.py --clean      # Remove build artifacts

Requires: cython, setuptools
"""

import argparse
import os
import shutil
import sys
from pathlib import Path

# Modules to compile — these contain the proprietary statistical engines
CYTHON_MODULES = [
    "evolution/phase2_engine.py",
    "evolution/phase3_engine.py",
    "evolution/phase4_engine.py",
    "evolution/phase5_engine.py",
    "evolution/knowledge_store.py",
    "evolution/license.py",
]

BUILD_DIR = Path("build")
DIST_DIR = Path("dist_compiled")


def inject_signing_key():
    """Inject production signing key into license.py before Cython compilation.

    Reads EVO_LICENSE_SIGNING_KEY from environment. If set, replaces the dev
    fallback key so the compiled binary embeds the production key. Users won't
    need the env var — the key is baked into the .so/.pyd.
    """
    key = os.environ.get("EVO_LICENSE_SIGNING_KEY")
    if not key:
        print("  No EVO_LICENSE_SIGNING_KEY set — using dev key (test builds only)")
        return False

    license_py = Path("evolution/license.py")
    content = license_py.read_text()
    marker = '_DEV_SIGNING_KEY = b"evo-license-v1-dev-key-replace-in-production"'
    if marker not in content:
        print("  Warning: signing key marker not found in license.py", file=sys.stderr)
        return False

    content = content.replace(marker, f'_DEV_SIGNING_KEY = b"{key}"')
    license_py.write_text(content)
    print("  Injected production signing key into license.py")
    return True


def check_cython():
    """Verify Cython is available."""
    try:
        import Cython
        print(f"Cython {Cython.__version__} available")
        return True
    except ImportError:
        print("Cython not installed. Install with: pip install cython", file=sys.stderr)
        return False


def clean():
    """Remove build artifacts."""
    removed = []
    if BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
        removed.append(str(BUILD_DIR))
    if DIST_DIR.exists():
        shutil.rmtree(DIST_DIR)
        removed.append(str(DIST_DIR))

    # Remove .c files generated by Cython
    for mod_path in CYTHON_MODULES:
        c_file = Path(mod_path).with_suffix(".c")
        if c_file.exists():
            c_file.unlink()
            removed.append(str(c_file))

    # Remove .so / .pyd files
    for mod_path in CYTHON_MODULES:
        base = Path(mod_path).stem
        parent = Path(mod_path).parent
        for ext in ("*.so", "*.pyd"):
            for f in parent.glob(f"{base}{ext}"):
                f.unlink()
                removed.append(str(f))
            # Also check for platform-specific names like module.cpython-311-darwin.so
            # Platform-specific names like module.cpython-311-darwin.so
            for f in parent.iterdir():
                if f.stem.startswith(base + ".") and f.name.endswith(ext.lstrip("*")):
                    f.unlink()
                    removed.append(str(f))

    if removed:
        print(f"Cleaned: {', '.join(removed)}")
    else:
        print("Nothing to clean")


def build():
    """Compile modules with Cython."""
    if not check_cython():
        sys.exit(1)

    # Inject production signing key before compilation (if available)
    key_injected = inject_signing_key()

    from Cython.Build import cythonize
    from setuptools import Distribution, Extension

    # Verify all source files exist
    missing = [m for m in CYTHON_MODULES if not Path(m).exists()]
    if missing:
        print(f"Missing source files: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)

    # Create extensions
    extensions = []
    for mod_path in CYTHON_MODULES:
        # Convert path to dotted module name: evolution/phase2_engine.py → evolution.phase2_engine
        mod_name = mod_path.replace("/", ".").replace("\\", ".").removesuffix(".py")
        extensions.append(Extension(mod_name, [mod_path]))

    print(f"Compiling {len(extensions)} modules...")

    # Cythonize
    ext_modules = cythonize(
        extensions,
        compiler_directives={
            "language_level": "3",
            "boundscheck": False,
            "wraparound": False,
        },
        quiet=False,
    )

    # Build using setuptools
    dist = Distribution({"ext_modules": ext_modules})
    dist.parse_config_files()

    # Build in-place (puts .so next to .py)
    from setuptools.command.build_ext import build_ext
    cmd = build_ext(dist)
    cmd.inplace = True
    cmd.ensure_finalized()
    cmd.run()

    # Restore original license.py if we injected a key (don't leak to source)
    if key_injected:
        import subprocess
        subprocess.run(["git", "checkout", "evolution/license.py"], capture_output=True)
        print("  Restored original license.py (key is in compiled binary only)")

    # Verify output
    compiled = []
    for mod_path in CYTHON_MODULES:
        base = Path(mod_path).stem
        parent = Path(mod_path).parent
        for f in parent.glob(f"{base}*.so"):
            compiled.append(str(f))
        for f in parent.glob(f"{base}*.pyd"):
            compiled.append(str(f))

    if compiled:
        print(f"\nCompiled {len(compiled)} extension(s):")
        for c in compiled:
            print(f"  {c}")
    else:
        print("\nWarning: no compiled files found after build", file=sys.stderr)

    return compiled


def package(compiled_files: list[str]):
    """Copy compiled files to dist_compiled/ for distribution."""
    DIST_DIR.mkdir(exist_ok=True)

    for f in compiled_files:
        dest = DIST_DIR / f
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(f, dest)
        print(f"  Packaged: {dest}")

    # Copy non-compiled modules too (adapters, CLI, etc.)
    open_source = [
        "evolution/__init__.py",
        "evolution/cli.py",
        "evolution/orchestrator.py",
        "evolution/registry.py",
        "evolution/config.py",
        "evolution/friendly.py",
        "evolution/prescan.py",
        "evolution/pr_comment.py",
        "evolution/kb_export.py",
        "evolution/kb_security.py",
        "evolution/kb_sync.py",
        "evolution/report_generator.py",
        "evolution/adapter_validator.py",
        "evolution/investigator.py",
        "evolution/fixer.py",
    ]
    for f in open_source:
        if Path(f).exists():
            dest = DIST_DIR / f
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, dest)

    # Copy entire adapter directories
    for adapter_dir in Path("evolution/adapters").iterdir():
        if adapter_dir.is_dir():
            dest = DIST_DIR / adapter_dir
            if dest.exists():
                shutil.rmtree(dest)
            shutil.copytree(adapter_dir, dest)

    # Copy data files
    data_dir = Path("evolution/data")
    if data_dir.exists():
        dest = DIST_DIR / data_dir
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(data_dir, dest)

    # Copy agents
    agents_dir = Path("evolution/agents")
    if agents_dir.exists():
        dest = DIST_DIR / agents_dir
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(agents_dir, dest)

    print(f"\nDist package ready at: {DIST_DIR}/")


def main():
    parser = argparse.ArgumentParser(description="Build Cython extensions for Evolution Engine")
    parser.add_argument("--check", action="store_true", help="Check if Cython is available")
    parser.add_argument("--clean", action="store_true", help="Remove build artifacts")
    parser.add_argument("--package", action="store_true", help="Package compiled + open-source into dist_compiled/")
    args = parser.parse_args()

    if args.check:
        sys.exit(0 if check_cython() else 1)
    elif args.clean:
        clean()
    else:
        compiled = build()
        if args.package and compiled:
            package(compiled)


if __name__ == "__main__":
    main()
