"""
Evolution Engine adapter for pytest-cov coverage reports.

Parses coverage.xml files generated by pytest-cov and yields testing events
with coverage metrics (line_rate, branch_rate, covered/missing lines).

This is a reference implementation demonstrating the full adapter lifecycle:
scaffold → develop → validate → security-check → publish.

Usage:
    pip install -e .
    evo adapter validate evo_pytest_cov.PytestCovAdapter --args '{"path": "."}'
    evo adapter security-check evo_pytest_cov
"""

import os
import xml.etree.ElementTree as ET
from pathlib import Path


class PytestCovAdapter:
    """Adapter for pytest-cov coverage.xml reports."""

    source_family = "testing"
    source_type = "pytest_cov"
    ordering_mode = "temporal"
    attestation_tier = "weak"

    def __init__(self, path="."):
        self.repo_path = Path(path).resolve()
        self.source_id = f"pytest_cov:{self.repo_path}"

    def iter_events(self):
        """Yield coverage events from coverage.xml files."""
        coverage_file = self.repo_path / "coverage.xml"
        if not coverage_file.exists():
            return

        tree = ET.parse(str(coverage_file))
        root = tree.getroot()

        # Extract coverage metrics
        line_rate = float(root.get("line-rate", "0"))
        branch_rate = float(root.get("branch-rate", "0"))
        lines_valid = int(root.get("lines-valid", "0"))
        lines_covered = int(root.get("lines-covered", "0"))
        branches_valid = int(root.get("branches-valid", "0"))
        branches_covered = int(root.get("branches-covered", "0"))

        # Count packages
        packages = root.findall(".//package")
        packages_covered = len(packages)

        # Try to get current commit SHA from .git
        commit_sha = self._get_commit_sha()

        yield {
            "source_family": self.source_family,
            "source_type": self.source_type,
            "source_id": self.source_id,
            "ordering_mode": self.ordering_mode,
            "attestation": {"trust_tier": self.attestation_tier},
            "payload": {
                "coverage_file": "coverage.xml",
                "line_rate": line_rate,
                "branch_rate": branch_rate,
                "packages_covered": packages_covered,
                "lines_covered": lines_covered,
                "lines_missing": lines_valid - lines_covered,
                "branches_covered": branches_covered,
                "branches_missing": branches_valid - branches_covered,
                "trigger": {"commit_sha": commit_sha},
            },
        }

    def _get_commit_sha(self) -> str:
        """Get the current git commit SHA by reading .git/HEAD directly."""
        try:
            head_file = self.repo_path / ".git" / "HEAD"
            if not head_file.exists():
                return ""
            content = head_file.read_text().strip()
            # If HEAD is a ref (e.g. "ref: refs/heads/main"), resolve it
            if content.startswith("ref: "):
                ref_path = self.repo_path / ".git" / content[5:]
                if ref_path.exists():
                    return ref_path.read_text().strip()
                return ""
            # Detached HEAD — content is the SHA itself
            return content
        except OSError:
            return ""


def register():
    """Register this adapter with Evolution Engine's plugin system."""
    return [
        {
            "pattern": "coverage.xml",
            "adapter_name": "pytest_cov",
            "family": "testing",
            "adapter_class": "evo_pytest_cov.PytestCovAdapter",
        },
    ]
