"""
Evolution Engine adapter for Jest coverage reports.

Parses coverage/coverage-summary.json files generated by Jest and yields
testing events with line, branch, function, and statement coverage metrics.

This is a reference implementation for JavaScript/TypeScript projects,
demonstrating the adapter development flow alongside the pytest-cov adapter.

Usage:
    pip install -e .
    evo adapter validate evo_jest_cov.JestCovAdapter --args '{"path": "."}'
    evo adapter security-check evo_jest_cov
"""

import hashlib
import json
from pathlib import Path


class JestCovAdapter:
    """Adapter for Jest coverage-summary.json reports."""

    source_family = "testing"
    source_type = "jest_cov"
    ordering_mode = "temporal"
    attestation_tier = "weak"

    def __init__(self, path="."):
        self.repo_path = Path(path).resolve()
        self.source_id = f"jest_cov:{self.repo_path}"

    def iter_events(self):
        """Yield coverage events from coverage/coverage-summary.json files."""
        coverage_file = self.repo_path / "coverage" / "coverage-summary.json"
        if not coverage_file.exists():
            return

        data = json.loads(coverage_file.read_text())

        total = data.get("total", {})
        if not total:
            return

        lines = total.get("lines", {})
        branches = total.get("branches", {})
        functions = total.get("functions", {})
        statements = total.get("statements", {})

        # Count packages (top-level keys excluding "total")
        packages_covered = sum(1 for k in data if k != "total")

        commit_sha = self._get_commit_sha()

        # Content-hash for dedup
        report_hash = hashlib.sha256(
            coverage_file.read_bytes()
        ).hexdigest()[:16]

        yield {
            "source_family": self.source_family,
            "source_type": self.source_type,
            "source_id": self.source_id,
            "ordering_mode": self.ordering_mode,
            "attestation": {
                "trust_tier": self.attestation_tier,
                "report_hash": report_hash,
            },
            "payload": {
                "coverage_file": "coverage/coverage-summary.json",
                "line_rate": lines.get("pct", 0) / 100,
                "branch_rate": branches.get("pct", 0) / 100,
                "function_rate": functions.get("pct", 0) / 100,
                "statement_rate": statements.get("pct", 0) / 100,
                "lines_covered": lines.get("covered", 0),
                "lines_missing": lines.get("total", 0) - lines.get("covered", 0),
                "branches_covered": branches.get("covered", 0),
                "branches_missing": branches.get("total", 0) - branches.get("covered", 0),
                "functions_covered": functions.get("covered", 0),
                "functions_missing": functions.get("total", 0) - functions.get("covered", 0),
                "packages_covered": packages_covered,
                "trigger": {"commit_sha": commit_sha},
            },
        }

    def _get_commit_sha(self) -> str:
        """Get the current git commit SHA by reading .git/HEAD directly."""
        try:
            head_file = self.repo_path / ".git" / "HEAD"
            if not head_file.exists():
                return ""
            content = head_file.read_text().strip()
            if content.startswith("ref: "):
                ref_path = self.repo_path / ".git" / content[5:]
                if ref_path.exists():
                    return ref_path.read_text().strip()
                return ""
            return content
        except OSError:
            return ""


def register():
    """Register this adapter with Evolution Engine's plugin system."""
    return [
        {
            "pattern": "jest.config.js",
            "adapter_name": "jest_cov",
            "family": "testing",
            "adapter_class": "evo_jest_cov.JestCovAdapter",
        },
    ]
