"""
Project initialization for Evolution Engine.

Detects environment (Git repo, CI provider, etc.) and helps users
set up the right integration path:
  1. CLI only — explore manually with evo analyze / evo report
  2. Automated hooks — auto-analyze on commit/push
  3. GitHub Action / GitLab CI — CI-driven analysis with PR/MR comments
  4. All of the above

Usage:
    from evolution.init import ProjectInit
    pi = ProjectInit(repo_path=".")
    env = pi.detect_environment()
    pi.setup(path="hooks")
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any, Optional

from evolution.config import EvoConfig
from evolution.hooks import HookManager


# ─── Valid integration paths ───

_VALID_PATHS = ("cli", "hooks", "action", "all")


# ─── Workflow Template ───

_WORKFLOW_TEMPLATE = """\
# Evolution Engine — CI analysis workflow
# Generated by: evo init
# Docs: https://github.com/codequal/evolution-engine

name: Evolution Engine

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Evolution Engine Analyze
        uses: alpsla/evolution-engine@v1
        with:
          github-token: ${{{{ secrets.GITHUB_TOKEN }}}}
{families_line}{license_line}
      # ── Pro Features (uncomment to enable) ──
      # - name: AI Investigation
      #   uses: alpsla/evolution-engine@v1
      #   with:
      #     investigate: "true"
      #     anthropic-api-key: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
      #
      # - name: Inline Fix Suggestions
      #   uses: alpsla/evolution-engine@v1
      #   with:
      #     suggest-fixes: "true"
      #     investigate: "true"
      #     anthropic-api-key: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
"""


# ─── GitLab CI Template ───

_GITLAB_CI_TEMPLATE = """\
# Evolution Engine — GitLab CI pipeline
# Generated by: evo init
# Docs: https://github.com/codequal/evolution-engine
#
# Required CI/CD variables:
#   GITLAB_TOKEN — project access token with api scope (Settings > CI/CD > Variables)
#
# Optional CI/CD variables:
#   EVO_WEBHOOK_URL — acceptance webhook (e.g. https://codequal.dev/api/accept)

stages:
  - analyze
  - comment

# ── Helper: find existing EE note ID ──
.evo-find-note: &evo-find-note |
  EXISTING_NOTE_ID=$(curl -sf \\
    --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \\
    "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes?per_page=100" \\
    | python3 -c "
  import sys, json
  notes = json.load(sys.stdin)
  for n in notes:
      if '## Evolution Engine' in n.get('body', ''):
          print(n['id'])
          break
  " 2>/dev/null || true)

# ── Helper: post or update MR note ──
.evo-post-note: &evo-post-note |
  if [ -n "$EXISTING_NOTE_ID" ]; then
    curl -sf --request PUT \\
      --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \\
      --header "Content-Type: application/json" \\
      --data "$(python3 -c "import json,sys; print(json.dumps({{'body': open('.evo/comment.md').read()}}))")" \\
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes/$EXISTING_NOTE_ID" \\
      > /dev/null
  else
    curl -sf --request POST \\
      --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \\
      --header "Content-Type: application/json" \\
      --data "$(python3 -c "import json,sys; print(json.dumps({{'body': open('.evo/comment.md').read()}}))")" \\
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes" \\
      > /dev/null
  fi

# ── Stage 1: Run EE analysis ──
evo-analyze:
  stage: analyze
  image: python:3.11-slim
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    key: evo-$CI_MERGE_REQUEST_IID
    paths:
      - .evo/
  script:
    - apt-get update -qq && apt-get install -y -qq git > /dev/null 2>&1
    - pip install evolution-engine{version_pin}
    - |
      # Pull permanent acceptances from webhook
      if [ -n "$EVO_WEBHOOK_URL" ]; then
        curl -sf "$EVO_WEBHOOK_URL?repo=$CI_PROJECT_PATH&scope=permanent" -o /tmp/accepted.json 2>/dev/null || true
        if [ -f /tmp/accepted.json ]; then
          mkdir -p .evo
          cp /tmp/accepted.json .evo/accepted.json
        fi
      fi
    - |
      # Push permanent acceptances from local commit to webhook
      if [ -n "$EVO_WEBHOOK_URL" ] && [ -f .evo/accepted.json ]; then
        python3 -c "
      import json, urllib.request
      with open('.evo/accepted.json') as f:
          data = json.load(f)
      permanent = [a for a in data if a.get('scope') == 'permanent']
      if permanent:
          payload = json.dumps({{'repo': '$CI_PROJECT_PATH', 'accepted': permanent}}).encode()
          req = urllib.request.Request('$EVO_WEBHOOK_URL', data=payload,
              headers={{'Content-Type': 'application/json'}}, method='POST')
          urllib.request.urlopen(req, timeout=10)
      " 2>/dev/null || true
      fi
    - |
      # Save previous advisory for verification on next push
      if [ -f .evo/phase5/advisory.json ]; then
        cp .evo/phase5/advisory.json .evo/phase5/advisory.json.prev
      fi
    - evo analyze .{families_flag} --quiet
    - |
      # Run verification if previous advisory exists
      if [ -f .evo/phase5/advisory.json.prev ] && [ -f .evo/phase5/advisory.json ]; then
        evo verify .evo/phase5/advisory.json.prev --path . --quiet || true
      fi
    - |
      # Collect sources info for comment
      evo sources --json > .evo/sources.json 2>/dev/null || true
  artifacts:
    paths:
      - .evo/phase5/
      - .evo/sources.json
    expire_in: 7 days

# ── Stage 2: Post/update MR comment ──
evo-comment:
  stage: comment
  image: python:3.11-slim
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  needs:
    - evo-analyze
  script:
    - apt-get update -qq && apt-get install -y -qq curl > /dev/null 2>&1
    - pip install evolution-engine{version_pin}
    - |
      if [ ! -f .evo/phase5/advisory.json ]; then
        echo "No advisory found, skipping comment."
        exit 0
      fi
    - |
      # Build format_comment flags
      EXTRA_FLAGS=""
      if [ -f .evo/phase5/investigation_prompt.txt ]; then
        EXTRA_FLAGS="$EXTRA_FLAGS --prompt .evo/phase5/investigation_prompt.txt"
      fi
      if [ -f .evo/sources.json ]; then
        EXTRA_FLAGS="$EXTRA_FLAGS --sources .evo/sources.json"
      fi
      # Choose verification or initial advisory comment
      if [ -f .evo/phase5/verification.json ]; then
        RESIDUAL_FLAG=""
        if [ -f .evo/phase5/residual_prompt.txt ]; then
          RESIDUAL_FLAG="--residual-prompt .evo/phase5/residual_prompt.txt"
        elif [ -f .evo/phase5/investigation_prompt.txt ]; then
          RESIDUAL_FLAG="--residual-prompt .evo/phase5/investigation_prompt.txt"
        fi
        python -m evolution.format_comment \\
          --verification .evo/phase5/verification.json \\
          $RESIDUAL_FLAG \\
          --ci-provider gitlab \\
          --output .evo/comment.md
      else
        python -m evolution.format_comment \\
          --advisory .evo/phase5/advisory.json \\
          $EXTRA_FLAGS \\
          --ci-provider gitlab \\
          --output .evo/comment.md
      fi
    - *evo-find-note
    - *evo-post-note

      # ── Pro Features (uncomment to enable) ──
      # Requires ANTHROPIC_API_KEY in CI/CD variables.
      #
      # Add after the 'evo analyze' line in evo-analyze:
      #   - |
      #     if [ -f .evo/phase5/advisory.json ]; then
      #       evo investigate . --agent anthropic
      #     fi
      #
      # For inline MR suggestions, add an evo-suggest job:
      # evo-suggest:
      #   stage: comment
      #   image: python:3.11-slim
      #   rules:
      #     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      #   needs:
      #     - evo-analyze
      #   script:
      #     - pip install evolution-engine
      #     - |
      #       if [ -f .evo/investigation/report.json ]; then
      #         evo suggest . --ci-provider gitlab
      #       fi
"""


# ─── Hint messages for first runs ───

_HINTS = {
    "cli": (
        "Tip: You can automate analysis on every commit with git hooks.\n"
        "Run: evo init --path hooks"
    ),
    "hooks": (
        "Tip: You can add CI-powered analysis with MR/PR comments.\n"
        "Run: evo init --path action"
    ),
    "action": (
        "Tip: For local analysis between CI runs, install git hooks.\n"
        "Run: evo init --path hooks"
    ),
    "all": (
        "Tip: All integrations are set up. Run 'evo analyze .' to try it out."
    ),
}


# ─── ProjectInit ───

class ProjectInit:
    """Guided project initialization for Evolution Engine.

    Detects the project environment and sets up integration paths
    (CLI, hooks, GitHub Action, or all).

    Parameters
    ----------
    repo_path : str or Path
        Path to the repository root.
    evo_dir : str or Path, optional
        Override for the ``.evo/`` directory location.  Defaults to
        ``<repo_path>/.evo/``.
    config : EvoConfig, optional
        User configuration.  A fresh ``EvoConfig()`` is loaded if omitted.
    """

    def __init__(
        self,
        repo_path: str | Path,
        evo_dir: Optional[str | Path] = None,
        config: Optional[EvoConfig] = None,
    ):
        self.repo_path = Path(repo_path).resolve()
        self.evo_dir = Path(evo_dir).resolve() if evo_dir else self.repo_path / ".evo"
        self.config = config or EvoConfig()

    # ── Public API ──

    def detect_environment(self) -> dict[str, Any]:
        """Detect the project environment and return a summary dict.

        Returns
        -------
        dict
            Keys: is_git_repo, has_github, has_workflows, has_evo,
            has_evo_action, has_gitlab, has_evo_gitlab, remote_url,
            repo_name, ci_provider, suggested_path.
        """
        is_git = (self.repo_path / ".git").exists()
        has_github = (self.repo_path / ".github").is_dir()
        has_workflows = (self.repo_path / ".github" / "workflows").is_dir()
        has_evo = self.evo_dir.is_dir()
        has_evo_action = self._check_evo_action() if has_workflows else False
        has_gitlab = (self.repo_path / ".gitlab-ci.yml").exists()
        has_evo_gitlab = self._check_evo_gitlab() if has_gitlab else False
        remote_url = self._get_remote_url() if is_git else None
        repo_name = self._extract_repo_name(remote_url)
        ci_provider = self._detect_ci_provider(has_github, has_gitlab, remote_url)
        suggested_path = "hooks" if is_git else "cli"

        return {
            "is_git_repo": is_git,
            "has_github": has_github,
            "has_workflows": has_workflows,
            "has_evo": has_evo,
            "has_evo_action": has_evo_action,
            "has_gitlab": has_gitlab,
            "has_evo_gitlab": has_evo_gitlab,
            "remote_url": remote_url,
            "repo_name": repo_name,
            "ci_provider": ci_provider,
            "suggested_path": suggested_path,
        }

    def setup(self, path: str, families: str = "") -> dict[str, Any]:
        """Perform setup for the chosen integration path.

        Parameters
        ----------
        path : str
            One of ``"cli"``, ``"hooks"``, ``"action"``, ``"all"``.
        families : str
            Comma-separated family filter (e.g. ``"git,ci"``).

        Returns
        -------
        dict
            ``{"ok": True, "path": ..., "actions": [...]}`` on success,
            or ``{"ok": False, "error": ...}`` on failure.
        """
        if path not in _VALID_PATHS:
            return {
                "ok": False,
                "error": f"Invalid path: {path!r}. Must be one of {_VALID_PATHS}",
            }

        actions: list[str] = []

        # All paths create the .evo directory
        self.evo_dir.mkdir(parents=True, exist_ok=True)
        actions.append(f"Created {self.evo_dir}")

        if path in ("cli", "all"):
            self._save_init_config("cli" if path == "cli" else "all")
            actions.append("Saved init config")

        if path in ("hooks", "all"):
            hm = HookManager(self.repo_path, config=self.config)
            result = hm.install()
            if result.get("ok"):
                actions.append(f"Installed {result['trigger']} hook")
            else:
                return {
                    "ok": False,
                    "error": f"Hook install failed: {result.get('error', 'unknown')}",
                }
            if path == "hooks":
                self._save_init_config("hooks")
                actions.append("Saved init config")

        if path in ("action", "all"):
            env = self.detect_environment()
            if env.get("ci_provider") == "gitlab":
                ci_result = self._write_gitlab_ci(families=families)
            else:
                ci_result = self._write_workflow(families=families)
            if ci_result["ok"]:
                if ci_result.get("skipped"):
                    actions.append("GitLab CI already configured for EE (skipped)")
                else:
                    actions.append(f"Created {ci_result['workflow_path']}")
            else:
                return {"ok": False, "error": ci_result["error"]}
            if path == "action":
                self._save_init_config("action")
                actions.append("Saved init config")

        if path == "all":
            self._save_init_config("all")
            actions.append("Saved init config")

        return {"ok": True, "path": path, "actions": actions}

    def generate_gitlab_ci(self, families: str = "", version_pin: str = "") -> str:
        """Return YAML content for a GitLab CI pipeline with EE.

        Parameters
        ----------
        families : str
            Comma-separated family filter to embed in the pipeline.
        version_pin : str
            Optional version pin for pip install (e.g. ``"==0.2.0"``).

        Returns
        -------
        str
            Complete YAML pipeline content.
        """
        families_flag = ""
        if families:
            families_flag = f" --families {families}"

        pin = ""
        if version_pin:
            pin = f"=={version_pin}"

        return _GITLAB_CI_TEMPLATE.format(
            families_flag=families_flag,
            version_pin=pin,
        )

    def generate_workflow(self, families: str = "", license_key: str = "") -> str:
        """Return YAML content for a GitHub Action workflow.

        Parameters
        ----------
        families : str
            Comma-separated family filter to embed in the workflow.
        license_key : str
            License key secret name to embed in the workflow.

        Returns
        -------
        str
            Complete YAML workflow content.
        """
        families_line = ""
        if families:
            families_line = f"          families: \"{families}\"\n"

        license_line = ""
        if license_key:
            license_line = (
                f"        env:\n"
                f"          EVO_LICENSE_KEY: ${{{{ secrets.{license_key} }}}}\n"
            )

        return _WORKFLOW_TEMPLATE.format(
            families_line=families_line,
            license_line=license_line,
        )

    def first_run_hint(self) -> Optional[str]:
        """Return a hint message for the first 3 runs, or None after that.

        Reads and increments ``init.first_run_count`` in user config.
        The hint suggests the next integration step based on the
        current integration path.
        """
        count = self.config.get("init.first_run_count", 0)
        if count >= 3:
            return None

        self.config.set("init.first_run_count", count + 1)

        integration = self.config.get("init.integration", "")
        if not integration:
            return (
                "Tip: Set up Evolution Engine for this project.\n"
                "Run: evo init"
            )

        return _HINTS.get(integration)

    # ── Internal helpers ──

    def _save_init_config(self, path: str) -> None:
        """Save integration path and reset first_run_count in config."""
        self.config.set("init.integration", path)
        self.config.set("init.first_run_count", 0)

    def _check_evo_action(self) -> bool:
        """Check if any workflow file references evolution."""
        workflows_dir = self.repo_path / ".github" / "workflows"
        if not workflows_dir.is_dir():
            return False
        for wf_file in workflows_dir.iterdir():
            if wf_file.is_file() and wf_file.suffix in (".yml", ".yaml"):
                try:
                    content = wf_file.read_text()
                    if "evolution" in content.lower():
                        return True
                except OSError:
                    continue
        return False

    def _check_evo_gitlab(self) -> bool:
        """Check if .gitlab-ci.yml references evolution."""
        ci_file = self.repo_path / ".gitlab-ci.yml"
        if not ci_file.is_file():
            return False
        try:
            content = ci_file.read_text()
            return "evolution" in content.lower()
        except OSError:
            return False

    def _detect_ci_provider(
        self,
        has_github: bool,
        has_gitlab: bool,
        remote_url: Optional[str],
    ) -> Optional[str]:
        """Detect CI provider from CI files and remote URL.

        Priority: explicit CI file > remote URL hint > None.
        When both CI files exist, remote URL is the tiebreaker.
        """
        if has_gitlab and not has_github:
            return "gitlab"
        if has_github and not has_gitlab:
            return "github"
        if has_gitlab and has_github:
            # Both present — tiebreak with remote URL
            if remote_url and "gitlab" in remote_url.lower():
                return "gitlab"
            return "github"
        # Neither CI file — check remote URL
        if remote_url:
            if "gitlab" in remote_url.lower():
                return "gitlab"
            if "github" in remote_url.lower():
                return "github"
        return None

    def _get_remote_url(self) -> Optional[str]:
        """Get git remote origin URL."""
        try:
            result = subprocess.run(
                ["git", "remote", "get-url", "origin"],
                capture_output=True,
                text=True,
                timeout=5,
                cwd=str(self.repo_path),
            )
            if result.returncode == 0:
                return result.stdout.strip()
        except Exception:
            pass
        return None

    def _extract_repo_name(self, remote_url: Optional[str]) -> str:
        """Extract repository name from remote URL or fall back to dir name."""
        if remote_url:
            # Handle SSH format: git@github.com:owner/repo.git
            # Handle HTTPS format: https://github.com/owner/repo.git
            name = remote_url.rstrip("/")
            if name.endswith(".git"):
                name = name[:-4]
            name = name.rsplit("/", 1)[-1]
            # Handle SSH colon-separated path
            if ":" in name:
                name = name.rsplit(":", 1)[-1]
            return name
        return self.repo_path.name

    def _write_workflow(self, families: str = "", license_key: str = "") -> dict[str, Any]:
        """Write the workflow YAML to .github/workflows/evolution.yml."""
        workflows_dir = self.repo_path / ".github" / "workflows"
        workflows_dir.mkdir(parents=True, exist_ok=True)

        wf_path = workflows_dir / "evolution.yml"
        content = self.generate_workflow(families=families, license_key=license_key)
        wf_path.write_text(content)

        return {"ok": True, "workflow_path": str(wf_path)}

    def _write_gitlab_ci(self, families: str = "", version_pin: str = "") -> dict[str, Any]:
        """Write or append EE jobs to .gitlab-ci.yml.

        If .gitlab-ci.yml exists without EE references, appends EE jobs.
        If it already has EE references, skips to avoid duplication.
        If it doesn't exist, creates it fresh.
        """
        ci_path = self.repo_path / ".gitlab-ci.yml"

        if ci_path.exists():
            existing = ci_path.read_text()
            if "evolution" in existing.lower():
                return {"ok": True, "workflow_path": str(ci_path), "skipped": True}
            # Append EE jobs to existing file
            ee_content = self.generate_gitlab_ci(families=families, version_pin=version_pin)
            # Add separator and append
            combined = existing.rstrip() + "\n\n" + ee_content
            ci_path.write_text(combined)
        else:
            content = self.generate_gitlab_ci(families=families, version_pin=version_pin)
            ci_path.write_text(content)

        return {"ok": True, "workflow_path": str(ci_path)}
