"""
Project initialization for Evolution Engine.

Detects environment (Git repo, CI provider, etc.) and helps users
set up the right integration path:
  1. CLI only — explore manually with evo analyze / evo report
  2. Automated hooks — auto-analyze on commit/push
  3. GitHub Action — CI-driven analysis with PR comments
  4. All of the above

Usage:
    from evolution.init import ProjectInit
    pi = ProjectInit(repo_path=".")
    env = pi.detect_environment()
    pi.setup(path="hooks")
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any, Optional

from evolution.config import EvoConfig
from evolution.hooks import HookManager


# ─── Valid integration paths ───

_VALID_PATHS = ("cli", "hooks", "action", "all")


# ─── Workflow Template ───

_WORKFLOW_TEMPLATE = """\
# Evolution Engine — CI analysis workflow
# Generated by: evo init
# Docs: https://github.com/codequal/evolution-engine

name: Evolution Engine

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Evolution Engine Analyze
        uses: codequal/evolution-engine-action@v1
        with:
          github-token: ${{{{ secrets.GITHUB_TOKEN }}}}
{families_line}{license_line}
      # ── Pro Features (uncomment to enable) ──
      # - name: AI Investigation
      #   uses: codequal/evolution-engine-action@v1
      #   with:
      #     investigate: "true"
      #     anthropic-api-key: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
      #
      # - name: Inline Fix Suggestions
      #   uses: codequal/evolution-engine-action@v1
      #   with:
      #     suggest-fixes: "true"
      #     investigate: "true"
      #     anthropic-api-key: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
"""


# ─── Hint messages for first runs ───

_HINTS = {
    "cli": (
        "Tip: You can automate analysis on every commit with git hooks.\n"
        "Run: evo init --path hooks"
    ),
    "hooks": (
        "Tip: You can add CI-powered analysis with PR comments.\n"
        "Run: evo init --path action"
    ),
    "action": (
        "Tip: For local analysis between CI runs, install git hooks.\n"
        "Run: evo init --path hooks"
    ),
    "all": (
        "Tip: All integrations are set up. Run 'evo analyze .' to try it out."
    ),
}


# ─── ProjectInit ───

class ProjectInit:
    """Guided project initialization for Evolution Engine.

    Detects the project environment and sets up integration paths
    (CLI, hooks, GitHub Action, or all).

    Parameters
    ----------
    repo_path : str or Path
        Path to the repository root.
    evo_dir : str or Path, optional
        Override for the ``.evo/`` directory location.  Defaults to
        ``<repo_path>/.evo/``.
    config : EvoConfig, optional
        User configuration.  A fresh ``EvoConfig()`` is loaded if omitted.
    """

    def __init__(
        self,
        repo_path: str | Path,
        evo_dir: Optional[str | Path] = None,
        config: Optional[EvoConfig] = None,
    ):
        self.repo_path = Path(repo_path).resolve()
        self.evo_dir = Path(evo_dir).resolve() if evo_dir else self.repo_path / ".evo"
        self.config = config or EvoConfig()

    # ── Public API ──

    def detect_environment(self) -> dict[str, Any]:
        """Detect the project environment and return a summary dict.

        Returns
        -------
        dict
            Keys: is_git_repo, has_github, has_workflows, has_evo,
            has_evo_action, remote_url, repo_name, suggested_path.
        """
        is_git = (self.repo_path / ".git").exists()
        has_github = (self.repo_path / ".github").is_dir()
        has_workflows = (self.repo_path / ".github" / "workflows").is_dir()
        has_evo = self.evo_dir.is_dir()
        has_evo_action = self._check_evo_action() if has_workflows else False
        remote_url = self._get_remote_url() if is_git else None
        repo_name = self._extract_repo_name(remote_url)
        suggested_path = "hooks" if is_git else "cli"

        return {
            "is_git_repo": is_git,
            "has_github": has_github,
            "has_workflows": has_workflows,
            "has_evo": has_evo,
            "has_evo_action": has_evo_action,
            "remote_url": remote_url,
            "repo_name": repo_name,
            "suggested_path": suggested_path,
        }

    def setup(self, path: str, families: str = "") -> dict[str, Any]:
        """Perform setup for the chosen integration path.

        Parameters
        ----------
        path : str
            One of ``"cli"``, ``"hooks"``, ``"action"``, ``"all"``.
        families : str
            Comma-separated family filter (e.g. ``"git,ci"``).

        Returns
        -------
        dict
            ``{"ok": True, "path": ..., "actions": [...]}`` on success,
            or ``{"ok": False, "error": ...}`` on failure.
        """
        if path not in _VALID_PATHS:
            return {
                "ok": False,
                "error": f"Invalid path: {path!r}. Must be one of {_VALID_PATHS}",
            }

        actions: list[str] = []

        # All paths create the .evo directory
        self.evo_dir.mkdir(parents=True, exist_ok=True)
        actions.append(f"Created {self.evo_dir}")

        if path in ("cli", "all"):
            self._save_init_config("cli" if path == "cli" else "all")
            actions.append("Saved init config")

        if path in ("hooks", "all"):
            hm = HookManager(self.repo_path, config=self.config)
            result = hm.install()
            if result.get("ok"):
                actions.append(f"Installed {result['trigger']} hook")
            else:
                return {
                    "ok": False,
                    "error": f"Hook install failed: {result.get('error', 'unknown')}",
                }
            if path == "hooks":
                self._save_init_config("hooks")
                actions.append("Saved init config")

        if path in ("action", "all"):
            wf_result = self._write_workflow(families=families)
            if wf_result["ok"]:
                actions.append(f"Created {wf_result['workflow_path']}")
            else:
                return {"ok": False, "error": wf_result["error"]}
            if path == "action":
                self._save_init_config("action")
                actions.append("Saved init config")

        if path == "all":
            self._save_init_config("all")
            actions.append("Saved init config")

        return {"ok": True, "path": path, "actions": actions}

    def generate_workflow(self, families: str = "", license_key: str = "") -> str:
        """Return YAML content for a GitHub Action workflow.

        Parameters
        ----------
        families : str
            Comma-separated family filter to embed in the workflow.
        license_key : str
            License key secret name to embed in the workflow.

        Returns
        -------
        str
            Complete YAML workflow content.
        """
        families_line = ""
        if families:
            families_line = f"          families: \"{families}\"\n"

        license_line = ""
        if license_key:
            license_line = (
                f"        env:\n"
                f"          EVO_LICENSE_KEY: ${{{{ secrets.{license_key} }}}}\n"
            )

        return _WORKFLOW_TEMPLATE.format(
            families_line=families_line,
            license_line=license_line,
        )

    def first_run_hint(self) -> Optional[str]:
        """Return a hint message for the first 3 runs, or None after that.

        Reads and increments ``init.first_run_count`` in user config.
        The hint suggests the next integration step based on the
        current integration path.
        """
        count = self.config.get("init.first_run_count", 0)
        if count >= 3:
            return None

        self.config.set("init.first_run_count", count + 1)

        integration = self.config.get("init.integration", "")
        if not integration:
            return (
                "Tip: Set up Evolution Engine for this project.\n"
                "Run: evo init"
            )

        return _HINTS.get(integration)

    # ── Internal helpers ──

    def _save_init_config(self, path: str) -> None:
        """Save integration path and reset first_run_count in config."""
        self.config.set("init.integration", path)
        self.config.set("init.first_run_count", 0)

    def _check_evo_action(self) -> bool:
        """Check if any workflow file references evolution."""
        workflows_dir = self.repo_path / ".github" / "workflows"
        if not workflows_dir.is_dir():
            return False
        for wf_file in workflows_dir.iterdir():
            if wf_file.is_file() and wf_file.suffix in (".yml", ".yaml"):
                try:
                    content = wf_file.read_text()
                    if "evolution" in content.lower():
                        return True
                except OSError:
                    continue
        return False

    def _get_remote_url(self) -> Optional[str]:
        """Get git remote origin URL."""
        try:
            result = subprocess.run(
                ["git", "remote", "get-url", "origin"],
                capture_output=True,
                text=True,
                timeout=5,
                cwd=str(self.repo_path),
            )
            if result.returncode == 0:
                return result.stdout.strip()
        except Exception:
            pass
        return None

    def _extract_repo_name(self, remote_url: Optional[str]) -> str:
        """Extract repository name from remote URL or fall back to dir name."""
        if remote_url:
            # Handle SSH format: git@github.com:owner/repo.git
            # Handle HTTPS format: https://github.com/owner/repo.git
            name = remote_url.rstrip("/")
            if name.endswith(".git"):
                name = name[:-4]
            name = name.rsplit("/", 1)[-1]
            # Handle SSH colon-separated path
            if ":" in name:
                name = name.rsplit(":", 1)[-1]
            return name
        return self.repo_path.name

    def _write_workflow(self, families: str = "", license_key: str = "") -> dict[str, Any]:
        """Write the workflow YAML to .github/workflows/evolution.yml."""
        workflows_dir = self.repo_path / ".github" / "workflows"
        workflows_dir.mkdir(parents=True, exist_ok=True)

        wf_path = workflows_dir / "evolution.yml"
        content = self.generate_workflow(families=families, license_key=license_key)
        wf_path.write_text(content)

        return {"ok": True, "workflow_path": str(wf_path)}
